export let accessories = [
    {
        "id": "0FLlxyin0oGnaWKcXHgk",
        "category": "accessories",
        "brand": "Evatik",
        "views": 0,
        "quantity": 82,
        "name": "Ray-Ban RB5169",
        "price": 123,
        "gender": "Male",
        "color": "gray",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/805289291015__002.png?impolicy=GL_parameters_transp_clone1440&width=1440"
    },
    {
        "id": "0FyuThz6KJeWpJt9KkHI",
        "category": "accessories",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8053672463323__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "brand": "Evatik",
        "name": "Armani Exchange",
        "views": 0,
        "quantity": 107,
        "color": "black",
        "gender": "Female",
        "price": 87
    },
    {
        "id": "0VtMHPBUx5f2IuCfdZt9",
        "category": "accessories",
        "brand": "Evatik",
        "views": 0,
        "color": "brown",
        "quantity": 122,
        "name": "Oakley OX8156",
        "gender": "Male",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/888392399779__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "price": 106
    },
    {
        "id": "0aeGTfWif5EgzY7u2eq5",
        "category": "accessories",
        "color": "azure",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8053672991338__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "price": 107,
        "brand": "Evatik",
        "views": 0,
        "quantity": 23,
        "gender": "Female",
        "name": "Ray-Ban RB5387"
    },
    {
        "id": "0iCineDPSTvJMDAGcacJ",
        "category": "accessories",
        "gender": "Female",
        "name": "Arnette AN7125",
        "brand": "Evatik",
        "views": 0,
        "quantity": 105,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/888392356437__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "price": 54,
        "color": "brown"
    },
    {
        "id": "0kswFPfGanpeAeKt6bZD",
        "category": "accessories",
        "quantity": 7,
        "name": "Ray-Ban RB6375",
        "price": 116,
        "brand": "Evatik",
        "views": 0,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8053672875485__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "gender": "Male",
        "color": "black"
    },
    {
        "id": "1QL3uRt0mXJ1lne697Iv",
        "category": "accessories",
        "gender": "Female",
        "name": "Vogue Eyewear",
        "color": "black",
        "price": 80,
        "brand": "Evatik",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597338943__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "quantity": 78,
        "views": 0
    },
    {
        "id": "1YWrBeB5F6P6ooAIBVV4",
        "category": "accessories",
        "price": 133,
        "quantity": 22,
        "color": "yellow",
        "name": "Ray-Ban RB5428",
        "gender": "Female",
        "views": 0,
        "brand": "Evatik",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597728621__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440"
    },
    {
        "id": "2NBv20UbpiDbKWAP6qgH",
        "category": "accessories",
        "name": "Burberry BE2318",
        "color": "blue",
        "price": 133,
        "quantity": 50,
        "gender": "Female",
        "brand": "Evatik",
        "views": 0,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597167000__002.png?impolicy=GL_parameters_transp_clone1440&width=1440"
    },
    {
        "id": "2PG1KPQJcuS4oCusagMc",
        "category": "accessories",
        "brand": "Evatik",
        "views": 0,
        "quantity": 2,
        "color": "gray",
        "price": 83,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/725125363273__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "gender": "Male",
        "name": "Michael Kors"
    },
    {
        "id": "2RLwSWAEtAAXjcBmvWXM",
        "category": "accessories",
        "color": "black",
        "name": "Vogue Eyewear",
        "gender": "Female",
        "price": 69,
        "quantity": 78,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597683692__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "brand": "Evatik",
        "views": 0
    },
    {
        "id": "2kiAyYit4wqIDUvGKKBy",
        "category": "accessories",
        "views": 0,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8053672902600__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "color": "black",
        "brand": "Evatik",
        "name": "Ralph by Ralph Lauren",
        "price": 77,
        "gender": "Female",
        "quantity": 16
    },
    {
        "id": "3BpdCiIHHO8APsI2TYqW",
        "category": "accessories",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8053672503371__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "price": 107,
        "brand": "Gucci",
        "views": 0,
        "name": "Ray-Ban RB7066",
        "quantity": 25,
        "color": "green",
        "gender": "Female"
    },
    {
        "id": "3C3MXy8AQDQ6jCRmbieM",
        "category": "accessories",
        "brand": "Gucci",
        "name": "MK4058 CARACAS",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/725125000321__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "gender": "Male",
        "quantity": 99,
        "color": "black",
        "price": 144,
        "views": 0
    },
    {
        "id": "4EJC9qc2w0eaU2MLPjG5",
        "category": "accessories",
        "brand": "Gucci",
        "name": "Coach HC5103B",
        "quantity": 103,
        "price": 114,
        "gender": "Female",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/725125013642__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "color": "green",
        "views": 0
    },
    {
        "id": "4gYK9sgkoJDy3oTB5xer",
        "category": "accessories",
        "name": "Armani Exchange",
        "brand": "Gucci",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/7895653176171__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "quantity": 1,
        "color": "gray",
        "views": 0,
        "price": 61,
        "gender": "Male"
    },
    {
        "id": "8FSu7zTlwDl8q4c1iMCp",
        "category": "accessories",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/725125375115__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "brand": "Gucci",
        "color": "gray",
        "gender": "Female",
        "price": 97,
        "views": 0,
        "name": "MK4088 SITKA",
        "quantity": 109
    },
    {
        "id": "8crA0sTYTJnZJrNIY6zT",
        "category": "accessories",
        "brand": "Gucci",
        "gender": "Male",
        "name": "RB6392 JA-JO",
        "price": 116,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8053672833232__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "color": "green",
        "quantity": 100,
        "views": 0
    },
    {
        "id": "8edtCCrVM9EeTnKjJApP",
        "category": "accessories",
        "color": "yello",
        "gender": "Female",
        "views": 0,
        "price": 114,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/888392476012__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "name": "Oakley OX8163",
        "brand": "Gucci",
        "quantity": 39
    },
    {
        "id": "9ASHQu91265UCixBHgNE",
        "category": "accessories",
        "name": "RB3694V JIM",
        "quantity": 39,
        "color": "yello",
        "brand": "Gucci",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597721769__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "gender": "Female",
        "price": 125,
        "views": 0
    },
    {
        "id": "9EWY6l0MK1zSsQSsnMab",
        "category": "accessories",
        "color": "black",
        "quantity": 83,
        "views": 0,
        "name": "RB7118 DEAN",
        "brand": "Gucci",
        "price": 95,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597297738__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "gender": "Female"
    },
    {
        "id": "AF1obXnji7dB41ts390S",
        "category": "accessories",
        "gender": "Male",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597602129__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "color": "black",
        "views": 0,
        "brand": "Gucci",
        "price": 80,
        "quantity": 36,
        "name": "Eyewear VO5420"
    },
    {
        "id": "BjznndDVHPnmvPH6suHG",
        "category": "accessories",
        "color": "blue",
        "views": 0,
        "gender": "Female",
        "quantity": 17,
        "name": "Oakley OX3187 ",
        "price": 99,
        "brand": "Gucci",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/888392089984__002.png?impolicy=GL_parameters_transp_clone1440&width=1440"
    },
    {
        "id": "CSOW4WolxHDjrDcKATBb",
        "category": "accessories",
        "name": "MK4030 VIVIANNA",
        "quantity": 102,
        "views": 0,
        "color": "black",
        "brand": "Gucci",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/725125961295__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "gender": "Female",
        "price": 144
    },
    {
        "id": "CeOgzI3UyJVWflzg9hpy",
        "category": "accessories",
        "views": 0,
        "color": "gray",
        "gender": "Female",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597598323__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "quantity": 7,
        "price": 191,
        "name": "Persol PO3286V",
        "brand": "Silhouette"
    },
    {
        "id": "CgHBSZyZ8KMONou39z4i",
        "category": "accessories",
        "quantity": 21,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/888392594358__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "brand": "Silhouette",
        "gender": "Female",
        "name": "Arnette AN7211",
        "color": "gray",
        "price": 89,
        "views": 0
    },
    {
        "id": "D8nx5kBDPkO9aQRzm2Qh",
        "category": "accessories",
        "color": "black",
        "views": 0,
        "name": "RB6486 OPTICS",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597730488__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "price": 151,
        "quantity": 77,
        "gender": "Male",
        "brand": "Silhouette"
    },
    {
        "id": "DcA623bUJhXxp02PYhPX",
        "category": "accessories",
        "brand": "Silhouette",
        "color": "gold",
        "name": "Kors MK4099",
        "quantity": 20,
        "price": 194,
        "gender": "Male",
        "views": 0,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/725125387835__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440"
    },
    {
        "id": "EaccDJLnO3h5l2x4VpK4",
        "category": "accessories",
        "price": 102,
        "quantity": 7,
        "views": 0,
        "brand": "Silhouette",
        "color": "black",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597161923__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "gender": "Male",
        "name": "Polo Ralph"
    },
    {
        "id": "FsWKQ1k0FWCyL45DVA7b",
        "category": "accessories",
        "brand": "Silhouette",
        "gender": "Male",
        "name": "Ban RB6450",
        "quantity": 22,
        "color": "yello",
        "price": 83,
        "views": 0,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597183352__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440"
    },
    {
        "id": "GZcKhgyvqdjtxwM12DJH",
        "category": "accessories",
        "quantity": 23,
        "brand": "Silhouette",
        "views": 0,
        "price": 55,
        "name": "GK2002",
        "gender": "Female",
        "color": "azure",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597235860__002.png?impolicy=GL_parameters_transp_clone1440&width=1440"
    },
    {
        "id": "GlRThzsAu1qEb5EAMGB7",
        "category": "accessories",
        "views": 0,
        "brand": "Silhouette",
        "quantity": 81,
        "price": 83,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/7895653245969__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "color": "black",
        "gender": "Female",
        "name": "Armani Exchange"
    },
    {
        "id": "HLvIqoCZFVV4BdJSfkqk",
        "category": "accessories",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/7895653216778__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "quantity": 96,
        "views": 0,
        "name": "Exchange AX3079",
        "price": 59,
        "color": "yellow",
        "brand": "Silhouette",
        "gender": "Female"
    },
    {
        "id": "HRbIUAgHWfUbzMHRpzXD",
        "category": "accessories",
        "brand": "Silhouette",
        "gender": "Female",
        "color": "brown",
        "name": "Armani EA1103",
        "price": 81,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8056597177368__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "views": 0,
        "quantity": 105
    },
    {
        "id": "IjSfxcY7y8Edbcp2k8q7",
        "category": "accessories",
        "name": "Coach HC6147U",
        "price": 90,
        "brand": "Silhouette",
        "color": "green",
        "quantity": 9,
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/725125115568__002.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "views": 0,
        "gender": "Male"
    },
    {
        "id": "InVrq2lKmQRK3MM5aZMT",
        "category": "accessories",
        "imgUrl": "https://assets.glasses.com/is/image/Glasses/8053672402049__STD__shad__qt.png?impolicy=GL_parameters_transp_clone1440&width=1440",
        "name": "RB6335 OPTICS",
        "brand": "Silhouette",
        "gender": "Female",
        "views": 0,
        "quantity": 16,
        "color": "black",
        "price": 125
    }
]