export let jewelleries = [
    {
        "id": "5GYzTvvGo0qecf0ZqqhN",
        "category": "jewelleries",
        "brand": "Gorjana",
        "views": 10,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-pendant/lily_cluster_by_harry_winston_diamond_pendant_in_platinum_pedpmqrflc_e-1h.png?rev=98be33d8d0de4275a70c59bd84a89ff6",
        "name": "Lily Cluster",
        "price": 1878,
        "gender": "Male",
        "quantity": 10,
        "color": "Orange"
    },
    {
        "id": "5YWvCM9HYQH6OGksasGm",
        "category": "jewelleries",
        "color": "Turquoise",
        "gender": "Male",
        "name": "Cluster Yellow",
        "price": 718,
        "views": 19,
        "quantity": 19,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-pendant/lily_cluster_by_harry_winston_diamond_pendant_in_yellow_gold_pedymqrflc_e-1.png?rev=f190d56971f248d8b91087911572b215",
        "brand": "Gorjana"
    },
    {
        "id": "8FLIvs1PDBLZhyDi8cDA",
        "category": "jewelleries",
        "color": "Red",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-rose-gold-diamond-pendant/lily_cluster_by_harry_winston_diamond_pendant_in_rose_gold_pedrmqrflc_e-1.png?rev=fdaf65734a404a37bc0e2719dff382a9",
        "name": "Cluster Rose",
        "views": 29,
        "gender": "Male",
        "quantity": 29,
        "brand": "Gorjana",
        "price": 575
    },
    {
        "id": "8ciU1z8f4OlSSKEeZ3fg",
        "category": "jewelleries",
        "color": "Fuscia",
        "quantity": 35,
        "brand": "Gorjana",
        "views": 35,
        "price": 1910,
        "name": "Cluster Small",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-small-platinum-diamond-pendant/lily_cluster_by_harry_winston_small_diamond_pendant_in_platinum_pedpsm1mlc_e-1h.png?rev=2d30aa97f56a44e19f3db00b8a847710",
        "gender": "Male"
    },
    {
        "id": "9Iuwzl2yzsJkRFtwNopp",
        "category": "jewelleries",
        "price": 575,
        "name": "Lily Cluster Diamond",
        "views": 34,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-small-yellow-gold-diamond-pendant/lily_cluster_by_harry_winston_small_diamond_pendant_in_yellow_gold_pedysm1mlc_e-1h.png?rev=fe8371340b4a4ec2b80a76db3d58eded",
        "brand": "Gorjana",
        "gender": "Female",
        "quantity": 34,
        "color": "Blue"
    },
    {
        "id": "9JI2fT1zU6gZtPdIvYYK",
        "category": "jewelleries",
        "color": "Yellow",
        "name": "Cluster Platinum",
        "views": 32,
        "price": 757,
        "brand": "Gorjana",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-bracelet/lily_cluster_by_harry_winston_bracelet_diamond_platinum_brdpsm1mlc_e-1.png?rev=dfa5fab0ca4d4f0aacfec958d029f0c5",
        "gender": "Female",
        "quantity": 32
    },
    {
        "id": "BrIm88DTIIco0Dwuwa1N",
        "category": "jewelleries",
        "name": "Cluster Bracelet",
        "views": 33,
        "color": "Yellow",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-bracelet/lily_cluster_by_harry_winston_bracelet_diamond_yellow_gold_brdysm1mlc_e-1.png?rev=42e2907fe4b3442cb34a23beb38948e2",
        "gender": "Male",
        "price": 260,
        "quantity": 33,
        "brand": "Gorjana"
    },
    {
        "id": "E6NbgHUgjOWUlXeOihxA",
        "category": "jewelleries",
        "color": "Maroon",
        "name": "Cluster Rose",
        "brand": "Gorjana",
        "gender": "Male",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-rose-gold-diamond-bracelet/lily_cluster_by_harry_winston_bracelet_diamond_rose_gold_brdrsm1mlc_e-1.png?rev=26d3a457a96145d483062ec0308779cb",
        "price": 2069,
        "quantity": 31,
        "views": 31
    },
    {
        "id": "FSOuvKuvMsBpMUvEYAr8",
        "category": "jewelleries",
        "gender": "Male",
        "name": "Cluster Platinum",
        "views": 27,
        "brand": "Gorjana",
        "quantity": 27,
        "price": 2086,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-ring/lily_cluster_by_harry_winston_ring_diamond_platinum_frdpmqrflc_e-1.png?rev=ee454dfc14614d118b63110f4313b8b8",
        "color": "Mauv"
    },
    {
        "id": "FtGxhH2PlajgHYHYnSML",
        "category": "jewelleries",
        "gender": "Male",
        "color": "Aquamarine",
        "views": 20,
        "price": 2646,
        "quantity": 20,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-ring/lily_cluster_by_harry_winston_ring_diamond_yellow_gold_frdymqrflc_e-1.png?rev=07ce92cfc07d48768d42f499bdb2ad04",
        "name": "Cluster Yellow",
        "brand": "Gorjana"
    },
    {
        "id": "Gn6ej2MLkZJX10aalSMg",
        "category": "jewelleries",
        "brand": "Gorjana",
        "quantity": 15,
        "views": 15,
        "name": "Lily Cluster",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-rose-gold-diamond-ring/lily_cluster_by_harry_winston_ring_diamond_rose_gold_frdrmqrflc_e-1.png?rev=95f9f75cc8274dd4bc3ac0af9c3d1782",
        "gender": "Male",
        "color": "Fuscia",
        "price": 1666
    },
    {
        "id": "I0yk0X8POFLvMkdgg5zI",
        "category": "jewelleries",
        "price": 2195,
        "views": 21,
        "quantity": 21,
        "color": "Purple",
        "name": "Cluster Platinum",
        "gender": "Male",
        "brand": "Gorjana",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-ring/lily_cluster_by_harry_winston_ring_diamond_platinum_frdpsm1mlc_e-1.png?rev=970f8ede5e274e01ab39498245d3b1d9"
    },
    {
        "id": "NOyx6N1Ofk34zTnMMtfO",
        "category": "jewelleries",
        "name": " Cluster Yellow",
        "gender": "Male",
        "color": "Yellow",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-ring/lily_cluster_by_harry_winston_ring_diamond_yellow_gold_frdysm1mlc_e-1.png?rev=c9a2a1b42c3843609b6fbb9e4301ca77",
        "views": 2,
        "quantity": 2,
        "brand": "Cartier",
        "price": 1840
    },
    {
        "id": "NkNIRFNyINJDbjloXMID",
        "category": "jewelleries",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-earrings/lily_cluster_by_harry_winston_earrings_diamond_platinum_eadpmqrflc_e-1.png?rev=7bed1875b3d64e86934dcacceb502064",
        "price": 589,
        "name": " Cluster Platinum",
        "gender": "Female",
        "color": "Khaki",
        "quantity": 9,
        "views": 9,
        "brand": "Cartier"
    },
    {
        "id": "OqMx1VwKTmAPPGGTSgt4",
        "category": "jewelleries",
        "imgUrl": "https://mc-068cf1fd-d5dd-4f68-a158-493250-cd.azurewebsites.net/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-earrings/lily_cluster_by_harry_winston_earrings_diamond_yellow_gold_eadymqrflc_e-1.png?rev=9f1b2e303a994f669f7fbb48e0c74712",
        "brand": "Cartier",
        "views": 1,
        "price": 2105,
        "name": "Lily Cluster",
        "gender": "Female",
        "color": "Fuscia",
        "quantity": 1
    },
    {
        "id": "PVzMJnLXVe7raVnJzbpi",
        "category": "jewelleries",
        "quantity": 7,
        "name": "Rose Gold Diamond ",
        "gender": "Female",
        "views": 7,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-rose-gold-diamond-earrings/lily_cluster_by_harry_winston_earrings_diamond_rose_gold_eadrmqrflc_e-1.png?rev=51c524dd350a4d7fb9e7d2ddab932f73",
        "color": "Maroon",
        "brand": "Cartier",
        "price": 833
    },
    {
        "id": "T2B848xkB7VYRN6HyABS",
        "category": "jewelleries",
        "color": "Turquoise",
        "brand": "Cartier",
        "gender": "Male",
        "price": 2530,
        "name": "Small Platinum ",
        "views": 30,
        "quantity": 30,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-small-platinum-diamond-earrings/lily_cluster_by_harry_winston_earrings_small_diamond_platinum_eadppo1mlc_e-1.png?rev=cb1a1ee8e53d4fe59e45aefc2fcd90b2"
    },
    {
        "id": "U9blkiBgG2XvDkRQuAQA",
        "category": "jewelleries",
        "brand": "Cartier",
        "color": "Khaki",
        "quantity": 17,
        "name": "Gold Diamond Earrings",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-small-yellow-gold-diamond-earrings/lily_cluster_by_harry_winston_earrings_small_diamond_yellow_gold_eadypo1mlc_e-1.png?rev=65033808f92741868576e21510ce44a1",
        "price": 2644,
        "views": 17,
        "gender": "Female"
    },
    {
        "id": "V5eG9BzEd9N0kqG9xYZ0",
        "category": "jewelleries",
        "name": "Earrings on Wire",
        "color": "Blue",
        "quantity": 12,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-small-platinum-diamond-earrings-on-wire/lily_cluster_by_harry_winston_earrings_diamond_platinum_eadpdr1mlc_e-1.png?rev=ac3055b62ced4ca2b942bf1c733c16ed",
        "views": 12,
        "price": 2392,
        "gender": "Male",
        "brand": "Cartier"
    },
    {
        "id": "VtWnvjn5Ek8TCLpmIGuK",
        "category": "jewelleries",
        "color": "Purple",
        "brand": "Cartier",
        "price": 646,
        "gender": "Female",
        "name": "Small Yellow Gold ",
        "views": 23,
        "quantity": 23,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-small-yellow-gold-diamond-earrings-on-wire/lily_cluster_by_harry_winston_earrings_diamond_yellow_gold_eadydr1mlc_e-1.png?rev=d800b80264df498c98f5f46c4761807e"
    },
    {
        "id": "ag96b8O9S0KZQIl1MPz2",
        "category": "jewelleries",
        "brand": "Cartier",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-bracelet/lily_cluster_by_harry_winston_bracelet_diamond_platinum_brdprd6mlc_e-1.png?rev=01832129ab014df28f13ddc1a81f696f",
        "gender": "Female",
        "views": 26,
        "color": "Green",
        "quantity": 26,
        "name": "Cluster Platinum",
        "price": 2756
    },
    {
        "id": "aiJCfuEAUQWow8MY2LDN",
        "category": "jewelleries",
        "color": "Puce",
        "views": 13,
        "name": "Robertacci",
        "quantity": 13,
        "price": 2790,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-bracelet/lily_cluster_by_harry_winston_bracelet_diamond_yellow_gold_brdyrd6mlc_e-1.png?rev=a714e59cece24246b1e597a7c7f5132e",
        "brand": "Cartier",
        "gender": "Female"
    },
    {
        "id": "cSsJt6wxsdvoAUCBwQvG",
        "category": "jewelleries",
        "quantity": 18,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-bangle-bracelet/lily_cluster_by_harry_winston_bracelet_diamond_platinum_brdpbasm65lc_e-1.png?rev=521177f4dcb1471f83277d16b5d7dc5c",
        "name": "Castello",
        "brand": "Cartier",
        "price": 1134,
        "views": 18,
        "color": "Mauv",
        "gender": "Female"
    },
    {
        "id": "fAH7BugyAEwghRWjL9gr",
        "category": "jewelleries",
        "price": 1670,
        "quantity": 24,
        "name": "Astin",
        "color": "Red",
        "brand": "Cartier",
        "gender": "Female",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-small-platinum-diamond-bangle-bracelet/lily_cluster_by_harry_winston_bracelet_diamond_platinum_brdpba1m6lc_e-1.png?rev=c53f112caf9648348f8965c2ec31022c",
        "views": 24
    },
    {
        "id": "gfuTG46sz5tNTI3oETyG",
        "category": "jewelleries",
        "quantity": 36,
        "color": "Mauv",
        "name": "Congdon",
        "views": 36,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-necklace/lily_cluster_by_harry_winston_necklace_diamond_platinum_nkdprd13mlc_e-1.png?rev=077b491c74784f3a9d69b26eb338aa4c",
        "gender": "Male",
        "price": 2884,
        "brand": "Pandora"
    },
    {
        "id": "hiErNWLBFWk4J5jQdcLB",
        "category": "jewelleries",
        "brand": "Pandora",
        "quantity": 25,
        "views": 25,
        "color": "Fuscia",
        "name": "Gowlett",
        "price": 1716,
        "gender": "Female",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-necklace/lily_cluster_by_harry_winston_necklace_diamond_yellow_gold_nkdyrd13mlc_e-1.png?rev=2ef6a76f73b2424195ed68f98f93a42f"
    },
    {
        "id": "jlJrcOyn9PdwrMKu0GrL",
        "category": "jewelleries",
        "color": "Blue",
        "quantity": 5,
        "gender": "Male",
        "name": "Meigh",
        "brand": "Pandora",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-sautoir-necklace/lily_cluster_by_harry_winston_necklace_platinum_nkdprd3mlc_e_1.png?rev=21bb8584d8764d2d818575bb5fad13e1",
        "price": 2373,
        "views": 5
    },
    {
        "id": "pt6y0P9hm9p9CZtOjtkD",
        "category": "jewelleries",
        "name": "Blasius",
        "views": 14,
        "price": 1390,
        "quantity": 14,
        "color": "Violet",
        "gender": "Male",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-yellow-gold-diamond-sautoir-necklace/lily_cluster_by_harry_winston_necklace_yellow_gold_nkdyrd3mlc_e_1.png?rev=6d3e7f9558b14a5d9ee93189912c47fd",
        "brand": "Pandora"
    },
    {
        "id": "qNYQH71LZEyXUkhhMzn6",
        "category": "jewelleries",
        "quantity": 4,
        "name": "Witard",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-round-brilliant-diamond-engagement-ring/lily_cluster_by_harry_winston_engagement_ring_diamond_rgdprd005lc_e-1.png?rev=e175f42b2c814640b302b3a6190b3fa9",
        "gender": "Male",
        "brand": "Pandora",
        "color": "Aquamarine",
        "price": 685,
        "views": 4
    },
    {
        "id": "qqSNGcR3ITuRqPUaHK7D",
        "category": "jewelleries",
        "brand": "Pandora",
        "price": 1304,
        "quantity": 28,
        "color": "Aquamarine",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/lily-cluster-by-harry-winston/lily-cluster-platinum-diamond-barrette/lily_cluster_by_harry_winston_barette_diamond_platinum_hadprdbarlc_e-1.png?rev=b48d5bb81bef4e5fbab6165731478cce",
        "name": "Bavage",
        "views": 28,
        "gender": "Male"
    },
    {
        "id": "snkuXxaD05yHBojgxg4C",
        "category": "jewelleries",
        "color": "Pink",
        "gender": "Female",
        "brand": "Pandora",
        "views": 6,
        "price": 2777,
        "quantity": 6,
        "name": "Bridgens",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/hw-logo-by-harry-winston/hw-logo-rose-gold-diamond-ring/hw_logo_by_harry_winston_wedding_band_diamond_rose_gold_wbdrrdlghwl_e-1.png?rev=88187749ab6340478ccb834dc84e7b64"
    },
    {
        "id": "ss9HDlSuScd4b7uBgR0u",
        "category": "jewelleries",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/hw-logo-by-harry-winston/hw-logo-white-gold-single-diamond-ring/hw_logo_by_harry_winston_wedding_band_diamond_wbdwrdbzhwl_e-1.png?rev=3563ecf3feaf4391b4af980cd51b0d52",
        "name": "McKinney",
        "price": 243,
        "views": 11,
        "brand": "Pandora",
        "gender": "Male",
        "quantity": 11,
        "color": "Blue"
    },
    {
        "id": "tm1ySMxyLSRsbCouZrKz",
        "category": "jewelleries",
        "brand": "Pandora",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/hw-logo-by-harry-winston/hw-logo-white-gold-diamond-ring/hw_logo_by_harry_winston_wedding_band_diamond_wbdwrdlghwl_e-1.png?rev=0e729902106d4241a1eb236d3b1f47b5",
        "color": "Red",
        "views": 3,
        "quantity": 3,
        "name": "Gillitt",
        "gender": "Male",
        "price": 305
    },
    {
        "id": "uCQfcGZkWbjD0Q8hvsJX",
        "category": "jewelleries",
        "quantity": 16,
        "price": 1154,
        "views": 16,
        "name": "Arents",
        "gender": "Male",
        "color": "Maroon",
        "brand": "Pandora",
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/hw-logo-by-harry-winston/hw-logo-yellow-gold-diamond-bangle-bracelet/hw_logo_by_harry_winston_bangle_diamond_yellow_gold_badyrd1mhwl_e-1.png?rev=98098ca4f77d4793aa32cacf5eb656ac"
    },
    {
        "id": "xhp7gGwV0mIxbMnhJezT",
        "category": "jewelleries",
        "price": 2887,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/hw-logo-by-harry-winston/hw-logo-white-gold-accent-diamond-bangle-bracelet/hw_logo_by_harry_winston_bangle_diamond_badwrd7mhwl_e-1.png?rev=d7e8615d54ed4ae99675dbbe2ac302c4",
        "quantity": 8,
        "name": "Torvey",
        "gender": "Female",
        "color": "Pink",
        "views": 8,
        "brand": "Pandora"
    },
    {
        "id": "ystd8JauJpgB1mYhoudw",
        "category": "jewelleries",
        "gender": "Female",
        "quantity": 22,
        "views": 22,
        "price": 734,
        "imgUrl": "https://www.harrywinston.com/-/media/project/harry-winston/corporate/harry-winston-int/fine-jewelry/hw-logo-by-harry-winston/hw-logo-round-brilliant-diamond-micropave-engagement-ring/hw_logo_engagement_ring_diamond_rgdprd010hwm_e-1.png?rev=519ece92d6b14b719e53a6c54c75f866",
        "name": "Copner",
        "brand": "Pandora",
        "color": "Turquoise"
    }
]